#!/bin/sh

# This sciprt uses the amplicon generated by summary.html and primer sequences generated by the respective
# order files with well number (from the output of the script QC_1.1_combinePrimerPlates.sh) 

# The output of the this script is /home/dyap/dyap_temp/Temp_cal-input
# Shared_chr10_78907562 CACATGGCCCCAACTTTTCCTCCTGCCTGATGTCTGGACCCACAGGGGACAGATGGTGGTCCCTGGTCACTGAAGTACCCACAGGTTTGATTATTGAGACTTTTATCTCTGTTGACTACAGGGAGGACCTGAATCAGTTTACATGGTTAAAATAAAAGCGCCATATACAAGGATAAAGCA DAH_primer_plate2:F03
# Format Name<tab>Sequence-in-upper-case<tab>Plate&well-ID

# This then calls Temp_cal.sh (which calculates the Tm of the amplicon and which reads the input file
# and generates the output file /home/dyap/dyap_temp/Temp_cal-output
# in the format (FS="_") Tm=$4, then FS="=", $2
# Shared_chr20_31940471_Tm=81.9_Length=154_ID=DAH_primer_plate2:F03

##############
tempfile="/home/dyap/dyap_temp/Temp_cal-input"
rm -f $tempfile

for sample in eIF4A3_NMD
	do
	echo $sample
	p3dir="/home/dyap/Projects/PrimerDesign/"$sample"/primer3"
	checkdir="/home/dyap/Projects/PrimerDesign/"$sample"/Annotate"
	checkfile=$checkdir"/"$sample"_summary.html"
	primerfile=$p3dir"/"$sample"_primer_order.txt"

	wd="/home/dyap/Projects/"$sample"/qPCR"

	# The primer plates are combined primers for unique and shared positions!

	cd $wd

	platefilename=$sample"_primer_plate"

	plates=`ls $platefilename*`

	for i in $plates
		do
			for j in `cat $i | grep Left_Ordered | grep Right_Ordered | awk -F"\t" '{print $2}' | sed 's/_/\ :\ /'`
				do
					seq=`grep -m1 -A1 $j $checkfile | grep -v $j | sed -e 's/<[^>]*>//g' | sed 's/\ \ (*.*)//' | tr -c 'ATCGatcg' 'X' | tr -d "X"`
					well=`grep $j $plates | awk -F"\t" '{print $1}'`
					left=`grep -m1 $j $primerfile | awk -F"," '{print $2}'`
					right=`grep -m1 $j $primerfile | awk -F"," '{print $3}'  | awk  'BEGIN {
                          			j = n = split("A C G T", t)
                                		for (i = 0; ++i <= n;)
                               		 	map[t[i]] = t[j--]
                                        	}
                        			{
                                		if (/LEFT/) print
                        			else {
                                			for (i = length; i; i--)
                                			printf "%s", map[substr($0, i, 1)]
                                			print x
                                			}
                        			}'`

					if [ ! -z "$seq" ]
						then
 						echo $j" "$seq | grep --color=always $left | grep --colour=always $right
						echo $j" "$seq" "$well >> $tempfile
					fi
				done

		echo $i"  done ------------------------"

		done

	done

echo "Calculating Amplicon Melting Temperatures..."

Temp_cal.sh

exit;
