#!/bin/sh

# This Script was written by Damian Yap (Apr 2013)
# To filter and add specific adaptors to primer3 generated primers for MiSeq
# Generate the order file and filtered AmpliconManifest

###############################################################
name="hct116_htert"	# Sample set naming
type="Ill" 		# Illumina adaptors
#type="Fld" 		# Fluidigm adaptors
Project="Splice"	# Project name
RefGen="Custom\Splice"	# Reference Genome for AmpliconManifest
ver="2"			# AmpliconManifest Version
###############################################################

dir="/home/dyap/public_html/"$Project"/"$name
p3dir="/home/dyap/Projects/PrimerDesign/"$Project"/primer3"
posdir="/home/dyap/Projects/PrimerDesign/"$Project"/positions"

##########################################
# Selected positions should be placed here
sourcefile=$posdir"/selected_positions.txt"

clear 
cd $dir


primerfile=$dir"/"$name"_primer_order.txt"
orderleft=$p3dir"/"$name"-"$type"-leftprimers.csv"
orderright=$p3dir"/"$name"-"$type"-rightprimers.csv"

						echo "WellPosition,Name,Sequence,Notes" > $orderleft
						echo "WellPosition,Name,Sequence,Notes" > $orderright

oldmanifest=$p3dir"/"$name".AmpliconManifest"
newmanifest=$p3dir"/"$name"-filtered.AmpliconManifest"

rm -fr $orderfile
rm -fr $newmanifest


	if [[ $type == "Ill" ]]
		then
		# Illlumina Adaptors (5'->3')
		fa="TCGTCGGCAGCGTCAGATGTGTATAAGAGACAG"
		ra="GTCTCGTGGGCTCGGAGATGTGTATAAGAGACAG"
	fi

	if [[ $type == "Fld" ]]
		then	
		# Forward adaptor for Fluidigm
		fa="ACACTGACGACATGGTTCTACA"
		# Reverse adaptor for Fluidigm (5'->3')
		ra="TACGGTAGCAGAGACTTGGTCT"
	fi

# If file has a header (manual input)
# cat $sourcefile | tail -n +2 | awk -F" " '{print $1}' > pattern
# IF file is generated by a script (no header)
cat $sourcefile | awk -F" " '{print $1}' > pattern

# Counters
alpha="A"
count=1
plate=1
		for i in `cat pattern`

		do
		
		label=`grep -m1 ^$i $primerfile | awk -F, '{print $1}' | awk -F_ '{print $1}'`
		left0=`grep -m1 ^$i $primerfile | awk -F, '{print $6}'`
		right0=`grep -m1 ^$i $primerfile | awk -F, '{print $8}'`


		echo $label,$left0,$right0

			if [[ $left0 != "" ]];
			
				then

				if [[ $right0 != "" ]];
			
					then

						if [[ $count -lt 10 ]];
							then 
								welpos=$alpha"0"$count
							else
								welpos=$alpha$count
						fi

						echo "Adding adaptors to sequences..."
						echo $welpos","$label"_L,"$fa$left0 >> $orderleft
						echo $welpos","$label"_R,"$ra$right0 >> $orderright

						echo "Filtering AmpliconManifest"
						grep ^$i -m1 $oldmanifest | awk -F"\t" '{print $1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6}' | sed 's/chr//' >> $newmanifest.tmp

				fi
			fi

			count=$((count+1))

			if [[ $count == 13 ]];
				then 
				count="1"
				if [[ $alpha == "I" ]]; 
					then 	alpha="A"
						plate=$((plate+1))
						orderleft=$p3dir"/"$name"-Ill-leftprimers"$plate".csv"
						orderright=$p3dir"/"$name"-Ill-rightprimers"$plate".csv"
				fi
				if [[ $alpha == "H" ]]; then alpha="I"; fi
				if [[ $alpha == "G" ]]; then alpha="H"; fi
				if [[ $alpha == "F" ]]; then alpha="G"; fi
				if [[ $alpha == "E" ]]; then alpha="F"; fi
				if [[ $alpha == "D" ]]; then alpha="E"; fi
				if [[ $alpha == "C" ]]; then alpha="D"; fi
				if [[ $alpha == "B" ]]; then alpha="C"; fi
				if [[ $alpha == "A" ]]; then alpha="B"; fi

			fi

		
		done

                echo "[Header]" > $newmanifest
                echo $name"  Manifest Version,"$ver >> $newmanifest
                echo "ReferenceGenome,"$RefGen >> $newmanifest
                echo "  " >> $newmanifest
                echo "[Regions]" >> $newmanifest
                echo "Name,Chromosome,Amplicon Start,Amplicon End,Upstream Probe Length,Downstream Probe Length,Comments" >> $newmanifest
		cat $newmanifest.tmp >> $newmanifest



		echo "Checking Amplicon Manifest for duplicates in the name column"

		dup=`awk -F'\t' '{print $1}' $newmanifest.tmp | sort | uniq -d | grep -F -f - $newmanifest.tmp`

			if [[ $dup != "" ]];
				then
				echo "DUPLICATES in AMPLICONMANIFEST"
				echo $dup
			fi
rm -f $p3dir/*.tmp
			
echo "done."
exit;
